spring:
  datasource:
    url: jdbc:mysql://192.168.56.103:3306/goods
    username: root
    password: root
    druid:
      initial-size: 1 #指定启动连接池时，初始建立的连接数量
      min-idle: 1 #指定必须保持连接的最小值
      max-active: 20 #指定连接池中最大的活跃连接数.
      max-wait: 60000 #指定连接池等待连接返回的最大等待时间，毫秒单位
      pool-prepared-statements: false #指定是否池化statements
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 1 #指定获取连接时连接校验的sql查询语句.
      test-on-borrow: false #当从连接池借用连接时，是否测试该连接.
      test-on-return: false #在连接归还到连接池时是否测试该连接.
      test-while-idle: true #当连接空闲时，是否执行连接测试.
      time-between-eviction-runs-millis: 60000 #指定空闲连接检查、废弃连接清理、空闲连接池大小调整之间的操作时间间隔
      min-evictable-idle-time-millis: 300000 #指定一个空闲连接最少空闲多久后可被清除.
      filters: stat, wall
      filter:
        stat:
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 10000
          merge-sql: true
        wall:
          db-type: mysql
          enabled: true

mybatis:
  #type-aliases-package: com.szunicom.sz_volunteer_union.model
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
